### ISSUE TITLE
Example of custom OAuthSwiftURLHandlerType

### ISSUE THREAD

**Issue by acoleman-apc** [dongri/OAuthSwift#102]
I would like to handle an oAuth request strictly in code - not in safari or a web view.   Is there an example of this type of custom OAuthSwiftURLHandlerType that I might be able to see?

Or is there perhaps a OAuthSwiftOpenURLInternally class that I have missed?

Thanks

**Comment by phimage** [comment]
No there is not, and that's not the work of a OAuth API to provide this because each website have its own page to login, the parameters name, the security etc...

You want to receive in your custom `OAuthSwiftURLHandlerType`the url provided by website
Then get the page programmatically(maybe with alamofire), make a POST to login with the good parameters because you already know an unique the user/password, and don't let user provide one
