### ISSUE TITLE
Foursquare authentication failing

### ISSUE THREAD

**Issue by nmorenor** [dongri/OAuthSwift#110]
Hi, I'm using OAuthSwift library on a project, and while doing Foursquare authentication I found something interesting inside the file OAuth2Swift.swift, when calling authorizeWithCallbackURL function I see that the returned url has both a query string and a fragment, it will be something like.

https://somehost/somepath?access_token=${atoken}#_=_

and because of that the responseParameters lose the access_token value with the code:

```
            var responseParameters: Dictionary<String, String> = Dictionary()
            if let query = url.query {
                responseParameters = query.parametersFromQueryString()
            }
            if ((url.fragment) != nil && url.fragment!.isEmpty == false) {
                responseParameters = url.fragment!.parametersFromQueryString()
            }
```

Cheers
Ignacio

**Comment by phimage** [comment]
There is a difference between Oauth1 and Oauth2 here
Oauth1 does'nt have this problem because there is an `else` between query and fragment

This is a solution to fix OAuth2, just add the `else` to choose only `query` if there is query and fragment

but we can also merge ? I make a PR for that : PR#111
PR can be closed if first solution is choosen

**Comment by nmorenor** [comment]
Is that the right thing to do?, or perhaps it could be better to concatenate both dictionaries :)

**Comment by phimage** [comment]
merge = concatenate, my second solution in my pull request
dongri will choose the right one if he has time ;)
