### ISSUE TITLE
Unable to configure in New Xcode 7.0 

### ISSUE THREAD

**Issue by sucharucrayonlabs** [dongri/OAuthSwift#120]

**Comment by phimage** [comment]
@sucharucrayonlabs please give a description such as error copy/paste 
 or close the issue...

**Comment by ogklacodepath** [comment]
I too get error when I try to `import OAuthSwift` . The error message is `Cannot load underlying module for OAuthSwift` .  I tried the dragging method and also pods installation . In both the methods I got this error. Not sure how to fix it.

**Comment by phimage** [comment]
Please give also more information when you need support

pod --version, xcode version (with build number, about screen), Podfile content (familiar or not with cocoapod, many people open project instead of workspace...)

google your problem, Sometimes remove derived data do the trick
http://stackoverflow.com/questions/31674885/cannot-load-underlying-module-for-alamofire
