### ISSUE TITLE
watchOS 2.0 support?

### ISSUE THREAD

**Issue by mohwaili** [dongri/OAuthSwift#135]
Will the watchOS 2.0 get any support?

**Comment by sucharuhasija** [comment]
Yes

**Comment by phimage** [comment]
must edit podspec and add
```
s.watchos.deployment_target = '2.0'
s.tvos.deployment_target = '9.0'
```
then add in code watchos ant tvos case (`#if os (watchOS)`) when there is 
```
#if os(iOS)
```

I can PR next week but don't know when PR will be merged

**Comment by phimage** [comment]
@mohwaili or @sucharuhasija  did you make development for watchos ?
Is it really necessary to make a framework compatible with watchos because when I create a project on xcode, all controller code seems to be executed on iOS, only UI is on the watch, but maybe I am wrong

I already add compatibility into podspec with one of my own project and see that watch os compile code with i386 , not x86_64 '(and have some bugs)

**Comment by mohwaili** [comment]
@phimage The problem I had is: my project has a shared framework  and I wanted to reuse it for the apple watch (since watch os2 it's only possible when duplicating the framework target). The user authentication is embedded in this shared framework, when installing the pod I received an error. So the quick fix was adding watch os2 support without changing anything in my shared framework.

The answer to your question: it's not necessary to add watch os2 support, I should have had considered this issue from the beginning. Now I've separated the login and authentication from the shared framework and everything is working.
